// src/components/public/AnnouncementList.tsx
import { useEffect, useState } from 'react';
import type {
	Announcement,
	AnnouncementList as AnnouncementListData,
	ApiResponse
} from '$lib/types';
import AnnouncementCard from './AnnouncementCard';
import styles from './AnnouncementList.module.css';

export default function AnnouncementList() {
	const [announcements, setAnnouncements] = useState<Announcement[]>([]);
	const [loading, setLoading] = useState(true);

	useEffect(() => {
		const controller = new AbortController();
		void (async () => {
			try {
				const response = await fetch('/api/announcements', { signal: controller.signal });
				if (!response.ok) throw new Error(`HTTP ${response.status}`);
				const data = (await response.json()) as ApiResponse<AnnouncementListData>;
				if (data.success && data.data) setAnnouncements(data.data.items);
			} catch (caught) {
				if (caught instanceof DOMException && caught.name === 'AbortError') return;
				console.error('Failed to load announcements:', caught);
			} finally {
				if (!controller.signal.aborted) setLoading(false);
			}
		})();

		return () => controller.abort();
	}, []);

	if (loading || announcements.length === 0) return null;

	return (
		<section className={styles['announcement-section']}>
			<div className={styles['section-header']}>
				<span className={styles['section-icon']} aria-hidden="true">
					📢
				</span>
				<h2 className={styles['section-title']}>公告</h2>
			</div>
			<div className={styles['announcement-list']}>
				{announcements.map((announcement) => (
					<AnnouncementCard key={announcement.id} announcement={announcement} />
				))}
			</div>
		</section>
	);
}

// src/lib/components/AnnouncementList.svelte
<script lang="ts">
	import type { Announcement, AnnouncementList as AnnouncementListData, ApiResponse } from '$lib/types';
	import AnnouncementCard from './AnnouncementCard.svelte';

	let announcements = $state<Announcement[]>([]);
	let loading = $state(true);

	async function loadAnnouncements() {
		try {
			const res = await fetch('/api/announcements');
			if (!res.ok) throw new Error(`HTTP ${res.status}`);
			const data: ApiResponse<AnnouncementListData> = await res.json();
			if (data.success && data.data) {
				announcements = data.data.items;
			}
		} catch (e) {
			console.error('Failed to load announcements:', e);
		} finally {
			loading = false;
		}
	}

	$effect(() => {
		loadAnnouncements();
	});
</script>

{#if !loading && announcements.length > 0}
	<section class="announcement-section">
		<div class="section-header">
			<span class="section-icon">📢</span>
			<h2 class="section-title">公告</h2>
		</div>
		<div class="announcement-list">
			{#each announcements as announcement (announcement.id)}
				<AnnouncementCard {announcement} />
			{/each}
		</div>
	</section>
{/if}

<style>
	.announcement-section {
		margin-bottom: 2rem;
	}

	.section-header {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		margin-bottom: 1rem;
	}

	.section-icon {
		font-size: 1.25rem;
	}

	.section-title {
		font-family: 'Fredoka', 'Nunito', sans-serif;
		font-size: 1.25rem;
		font-weight: 600;
		color: #6b4c9a;
		margin: 0;
	}

	.announcement-list {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}
</style>
