// src/components/admin/AnnouncementForm.tsx
import { useCallback, useEffect, useRef, useState } from 'react';

import '$lib/styles/admin-form.css';
import type { Announcement, AnnouncementFormData, AnnouncementList, ApiResponse } from '$lib/types';

import styles from './AnnouncementForm.module.css';
import { classNames } from './classNames';

const JSON_HEADERS = { 'Content-Type': 'application/json' } as const;

export default function AnnouncementForm() {
	const [announcements, setAnnouncements] = useState<Announcement[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState('');
	const [success, setSuccess] = useState('');
	const [editingId, setEditingId] = useState<string | null>(null);
	const [title, setTitle] = useState('');
	const [content, setContent] = useState('');
	const [visible, setVisible] = useState(true);
	const [pinned, setPinned] = useState(false);
	const [submitting, setSubmitting] = useState(false);
	const successTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
	const loadControllerRef = useRef<AbortController | null>(null);
	const mutationControllerRef = useRef<AbortController | null>(null);
	const actionControllersRef = useRef(new Map<string, AbortController>());
	const mountedRef = useRef(false);

	const showTemporarySuccess = useCallback((message: string) => {
		if (successTimerRef.current) clearTimeout(successTimerRef.current);
		setSuccess(message);
		successTimerRef.current = setTimeout(() => {
			setSuccess('');
			successTimerRef.current = null;
		}, 3000);
	}, []);

	const loadAnnouncements = useCallback(async (signal?: AbortSignal) => {
		setLoading(true);
		try {
			const response = await fetch('/api/admin/announcements', { signal });
			if (!response.ok) throw new Error(`HTTP ${response.status}`);
			const data = (await response.json()) as ApiResponse<AnnouncementList>;
			if (data.success && data.data) {
				setAnnouncements(data.data.items);
			} else {
				setError(data.error || '加载失败');
			}
		} catch (caught) {
			if (caught instanceof DOMException && caught.name === 'AbortError') return;
			setError('网络错误');
		} finally {
			if (!signal?.aborted) setLoading(false);
		}
	}, []);

	useEffect(() => {
		const controller = new AbortController();
		mountedRef.current = true;
		loadControllerRef.current = controller;
		queueMicrotask(() => {
			if (!controller.signal.aborted) void loadAnnouncements(controller.signal);
		});
		return () => {
			mountedRef.current = false;
			controller.abort();
			if (successTimerRef.current) clearTimeout(successTimerRef.current);
		};
	}, [loadAnnouncements]);

	function startEdit(item: Announcement) {
		setEditingId(item.id);
		setTitle(item.title);
		setContent(item.content);
		setVisible(item.visible);
		setPinned(item.pinned);
	}

	function cancelEdit() {
		setEditingId(null);
		setTitle('');
		setContent('');
		setVisible(true);
		setPinned(false);
	}

	async function reloadAnnouncements() {
		loadControllerRef.current?.abort();
		const controller = new AbortController();
		loadControllerRef.current = controller;
		await loadAnnouncements(controller.signal);
	}

	async function handleSubmit() {
		if (!title.trim() || !content.trim()) {
			setError('标题和内容不能为空');
			return;
		}
		if (submitting || mutationControllerRef.current) return;
		const controller = new AbortController();
		mutationControllerRef.current = controller;
		setSubmitting(true);
		setError('');
		setSuccess('');
		try {
			const body: AnnouncementFormData & { id?: string } = {
				title,
				content,
				visible,
				pinned,
				...(editingId && { id: editingId })
			};
			const response = await fetch('/api/admin/announcements', {
				method: editingId ? 'PUT' : 'POST',
				headers: JSON_HEADERS,
				body: JSON.stringify(body),
				signal: controller.signal
			});
			if (!response.ok) throw new Error(`HTTP ${response.status}`);
			const data = (await response.json()) as ApiResponse<Announcement>;
			if (controller.signal.aborted || !mountedRef.current) return;
			if (data.success) {
				showTemporarySuccess(editingId ? '更新成功' : '创建成功');
				cancelEdit();
				await reloadAnnouncements();
			} else {
				setError(data.error || '操作失败');
			}
		} catch (caught) {
			if (caught instanceof DOMException && caught.name === 'AbortError') return;
			if (mountedRef.current) setError('网络错误');
		} finally {
			if (mutationControllerRef.current === controller) {
				mutationControllerRef.current = null;
				if (mountedRef.current) setSubmitting(false);
			}
		}
	}

	async function updateAnnouncement(item: Announcement, patch: Partial<Announcement>) {
		const actionKey = `item:${item.id}`;
		if (actionControllersRef.current.has(actionKey)) return;
		const controller = new AbortController();
		actionControllersRef.current.set(actionKey, controller);
		try {
			const response = await fetch('/api/admin/announcements', {
				method: 'PUT',
				headers: JSON_HEADERS,
				body: JSON.stringify({ id: item.id, ...patch }),
				signal: controller.signal
			});
			if (!response.ok) throw new Error(`HTTP ${response.status}`);
			const data = (await response.json()) as ApiResponse;
			if (controller.signal.aborted || !mountedRef.current) return;
			if (data.success) {
				setError('');
				await reloadAnnouncements();
			} else {
				setError(data.error || '操作失败');
			}
		} catch (caught) {
			if (caught instanceof DOMException && caught.name === 'AbortError') return;
			if (mountedRef.current) setError('操作失败');
		} finally {
			actionControllersRef.current.delete(actionKey);
		}
	}

	async function deleteAnnouncement(id: string) {
		if (!window.confirm('确定删除这条公告吗？')) return;
		const actionKey = `item:${id}`;
		if (actionControllersRef.current.has(actionKey)) return;
		const controller = new AbortController();
		actionControllersRef.current.set(actionKey, controller);
		try {
			const response = await fetch('/api/admin/announcements', {
				method: 'DELETE',
				headers: JSON_HEADERS,
				body: JSON.stringify({ id }),
				signal: controller.signal
			});
			if (!response.ok) throw new Error(`HTTP ${response.status}`);
			const data = (await response.json()) as ApiResponse;
			if (controller.signal.aborted || !mountedRef.current) return;
			if (data.success) {
				showTemporarySuccess('删除成功');
				await reloadAnnouncements();
			} else {
				setError(data.error || '删除失败');
			}
		} catch (caught) {
			if (caught instanceof DOMException && caught.name === 'AbortError') return;
			if (mountedRef.current) setError('网络错误');
		} finally {
			actionControllersRef.current.delete(actionKey);
		}
	}

	return (
		<div className={styles.announcementManager}>
			<h3 className={styles.sectionTitle}>公告管理</h3>
			{error && (
				<div className={classNames(styles.alert, styles.alertError)} role="alert">
					{error}
				</div>
			)}
			{success && (
				<div className={classNames(styles.alert, styles.alertSuccess)} role="status">
					{success}
				</div>
			)}
			<div className={styles.formCard}>
				<h4 className={styles.formTitle}>{editingId ? '编辑公告' : '新增公告'}</h4>
				<div className={styles.formField}>
					<label htmlFor="ann-title" className="admin-label">
						标题
					</label>
					<input
						id="ann-title"
						value={title}
						onChange={(event) => setTitle(event.target.value)}
						placeholder="公告标题"
						className={classNames(styles.formInput, 'admin-input')}
					/>
				</div>
				<div className={styles.formField}>
					<label htmlFor="ann-content" className="admin-label">
						内容（Markdown）
					</label>
					<textarea
						id="ann-content"
						value={content}
						onChange={(event) => setContent(event.target.value)}
						placeholder="支持 **加粗**、[链接](url)、- 列表等 Markdown 格式"
						className={classNames(styles.formTextarea, 'admin-input')}
						rows={5}
					/>
				</div>
				<div className={styles.formRow}>
					<label className={styles.checkboxLabel}>
						<input
							type="checkbox"
							className="admin-checkbox"
							checked={visible}
							onChange={(event) => setVisible(event.target.checked)}
						/>
						<span>显示</span>
					</label>
					<label className={styles.checkboxLabel}>
						<input
							type="checkbox"
							className="admin-checkbox"
							checked={pinned}
							onChange={(event) => setPinned(event.target.checked)}
						/>
						<span>置顶</span>
					</label>
				</div>
				<div className={styles.formActions}>
					<button
						className="admin-btn admin-btn-primary"
						onClick={() => void handleSubmit()}
						disabled={submitting}
						type="button"
					>
						{submitting ? '提交中...' : editingId ? '保存修改' : '发布公告'}
					</button>
					{editingId && (
						<button className="admin-btn admin-btn-ghost" onClick={cancelEdit} type="button">
							取消
						</button>
					)}
				</div>
			</div>

			{loading ? (
				<p className={styles.loadingText}>加载中...</p>
			) : announcements.length === 0 ? (
				<p className={styles.emptyText}>暂无公告</p>
			) : (
				<div className={styles.list}>
					{announcements.map((item) => (
						<div className={styles.listItem} key={item.id}>
							<div className={styles.itemInfo}>
								<span className={styles.itemTitle}>
									{item.pinned ? '📌 ' : ''}
									{item.title}
								</span>
								<span className={classNames(styles.itemStatus, !item.visible && styles.hidden)}>
									{item.visible ? '显示' : '隐藏'}
								</span>
							</div>
							<div className={styles.itemActions}>
								<button
									className={styles.btnSm}
									onClick={() => void updateAnnouncement(item, { pinned: !item.pinned })}
									type="button"
								>
									{item.pinned ? '取消置顶' : '置顶'}
								</button>
								<button
									className={styles.btnSm}
									onClick={() => void updateAnnouncement(item, { visible: !item.visible })}
									type="button"
								>
									{item.visible ? '隐藏' : '显示'}
								</button>
								<button className={styles.btnSm} onClick={() => startEdit(item)} type="button">
									编辑
								</button>
								<button
									className={classNames(styles.btnSm, styles.btnDanger)}
									onClick={() => void deleteAnnouncement(item.id)}
									type="button"
								>
									删除
								</button>
							</div>
						</div>
					))}
				</div>
			)}
		</div>
	);
}

// src/lib/components/AnnouncementForm.svelte
<script lang="ts">
	import type {
		Announcement,
		AnnouncementList,
		AnnouncementFormData,
		ApiResponse
	} from '$lib/types';
	import '$lib/styles/admin-form.css';

	let announcements = $state<Announcement[]>([]);
	let loading = $state(true);
	let error = $state('');
	let success = $state('');

	// 表单状态
	let editingId = $state<string | null>(null);
	let formTitle = $state('');
	let formContent = $state('');
	let formVisible = $state(true);
	let formPinned = $state(false);
	let submitting = $state(false);

	const jsonHeaders = { 'Content-Type': 'application/json' } as const;

	async function loadAnnouncements() {
		loading = true;
		try {
			const res = await fetch('/api/admin/announcements');
			if (!res.ok) throw new Error(`HTTP ${res.status}`);
			const data: ApiResponse<AnnouncementList> = await res.json();
			if (data.success && data.data) {
				announcements = data.data.items;
			} else {
				error = data.error || '加载失败';
			}
		} catch {
			error = '网络错误';
		} finally {
			loading = false;
		}
	}

	function startEdit(item: Announcement) {
		editingId = item.id;
		formTitle = item.title;
		formContent = item.content;
		formVisible = item.visible;
		formPinned = item.pinned;
	}

	function cancelEdit() {
		editingId = null;
		formTitle = '';
		formContent = '';
		formVisible = true;
		formPinned = false;
	}

	async function handleSubmit() {
		if (!formTitle.trim() || !formContent.trim()) {
			error = '标题和内容不能为空';
			return;
		}
		submitting = true;
		error = '';
		success = '';
		try {
			const body: AnnouncementFormData & { id?: string } = {
				title: formTitle,
				content: formContent,
				visible: formVisible,
				pinned: formPinned,
				...(editingId && { id: editingId })
			};
			const method = editingId ? 'PUT' : 'POST';
			const res = await fetch('/api/admin/announcements', {
				method,
				headers: jsonHeaders,
				body: JSON.stringify(body)
			});
			if (!res.ok) throw new Error(`HTTP ${res.status}`);
			const data: ApiResponse<Announcement> = await res.json();
			if (data.success) {
				success = editingId ? '更新成功' : '创建成功';
				setTimeout(() => {
					success = '';
				}, 3000);
				cancelEdit();
				await loadAnnouncements();
			} else {
				error = data.error || '操作失败';
			}
		} catch {
			error = '网络错误';
		} finally {
			submitting = false;
		}
	}

	async function toggleVisible(item: Announcement) {
		try {
			const res = await fetch('/api/admin/announcements', {
				method: 'PUT',
				headers: jsonHeaders,
				body: JSON.stringify({ id: item.id, visible: !item.visible })
			});
			if (!res.ok) throw new Error(`HTTP ${res.status}`);
			const data: ApiResponse = await res.json();
			if (data.success) {
				error = '';
				await loadAnnouncements();
			}
		} catch {
			error = '操作失败';
		}
	}

	async function togglePinned(item: Announcement) {
		try {
			const res = await fetch('/api/admin/announcements', {
				method: 'PUT',
				headers: jsonHeaders,
				body: JSON.stringify({ id: item.id, pinned: !item.pinned })
			});
			if (!res.ok) throw new Error(`HTTP ${res.status}`);
			const data: ApiResponse = await res.json();
			if (data.success) {
				error = '';
				await loadAnnouncements();
			}
		} catch {
			error = '操作失败';
		}
	}

	async function deleteAnnouncement(id: string) {
		if (!confirm('确定删除这条公告吗？')) return;
		try {
			const res = await fetch('/api/admin/announcements', {
				method: 'DELETE',
				headers: jsonHeaders,
				body: JSON.stringify({ id })
			});
			if (!res.ok) throw new Error(`HTTP ${res.status}`);
			const data: ApiResponse = await res.json();
			if (data.success) {
				success = '删除成功';
				setTimeout(() => {
					success = '';
				}, 3000);
				await loadAnnouncements();
			} else {
				error = data.error || '删除失败';
			}
		} catch {
			error = '网络错误';
		}
	}

	$effect(() => {
		void loadAnnouncements();
	});
</script>

<div class="announcement-manager">
	<h3 class="section-title">公告管理</h3>

	{#if error}
		<div class="alert alert-error">{error}</div>
	{/if}
	{#if success}
		<div class="alert alert-success">{success}</div>
	{/if}

	<!-- 新增/编辑表单 -->
	<div class="form-card">
		<h4 class="form-title">{editingId ? '编辑公告' : '新增公告'}</h4>
		<div class="form-field">
			<label for="ann-title" class="admin-label">标题</label>
			<input
				id="ann-title"
				type="text"
				bind:value={formTitle}
				placeholder="公告标题"
				class="form-input admin-input"
			/>
		</div>
		<div class="form-field">
			<label for="ann-content" class="admin-label">内容（Markdown）</label>
			<textarea
				id="ann-content"
				bind:value={formContent}
				placeholder="支持 **加粗**、[链接](url)、- 列表等 Markdown 格式"
				class="form-textarea admin-input"
				rows="5"></textarea>
		</div>
		<div class="form-row">
			<label class="checkbox-label">
				<input type="checkbox" class="admin-checkbox" bind:checked={formVisible} />
				<span>显示</span>
			</label>
			<label class="checkbox-label">
				<input type="checkbox" class="admin-checkbox" bind:checked={formPinned} />
				<span>置顶</span>
			</label>
		</div>
		<div class="form-actions">
			<button
				class="btn admin-btn admin-btn-primary"
				onclick={handleSubmit}
				disabled={submitting}
				type="button"
			>
				{submitting ? '提交中...' : editingId ? '保存修改' : '发布公告'}
			</button>
			{#if editingId}
				<button class="btn admin-btn admin-btn-ghost" onclick={cancelEdit} type="button"
					>取消</button
				>
			{/if}
		</div>
	</div>

	<!-- 公告列表 -->
	{#if loading}
		<p class="loading-text">加载中...</p>
	{:else if announcements.length === 0}
		<p class="empty-text">暂无公告</p>
	{:else}
		<div class="list">
			{#each announcements as item (item.id)}
				<div class="list-item">
					<div class="item-info">
						<span class="item-title">{item.pinned ? '📌 ' : ''}{item.title}</span>
						<span class="item-status" class:hidden={!item.visible}
							>{item.visible ? '显示' : '隐藏'}</span
						>
					</div>
					<div class="item-actions">
						<button class="btn-sm" onclick={() => togglePinned(item)} type="button">
							{item.pinned ? '取消置顶' : '置顶'}
						</button>
						<button class="btn-sm" onclick={() => toggleVisible(item)} type="button">
							{item.visible ? '隐藏' : '显示'}
						</button>
						<button class="btn-sm" onclick={() => startEdit(item)} type="button">编辑</button>
						<button
							class="btn-sm btn-danger"
							onclick={() => deleteAnnouncement(item.id)}
							type="button">删除</button
						>
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>

<style>
	.announcement-manager {
		padding: 1rem 0;
	}

	.section-title {
		font-family: 'Fredoka', 'Nunito', sans-serif;
		font-size: 1.2rem;
		color: #6b4c9a;
		margin: 0 0 1rem;
	}

	.alert {
		padding: 0.75rem 1rem;
		border-radius: 12px;
		margin-bottom: 1rem;
		font-size: 0.9rem;
	}

	.alert-error {
		background: #fff0f0;
		color: #c0392b;
		border: 1px solid #fcc;
	}

	.alert-success {
		background: #f0fff4;
		color: #27ae60;
		border: 1px solid #aed6b8;
	}

	.form-card {
		background: rgba(255, 255, 255, 0.8);
		border: 1px solid rgba(107, 76, 154, 0.2);
		border-radius: 20px;
		padding: 1.25rem;
		margin-bottom: 1.5rem;
	}

	.form-title {
		font-size: 1rem;
		font-weight: 600;
		color: #6b4c9a;
		margin: 0 0 1rem;
	}

	.form-field {
		margin-bottom: 0.75rem;
	}

	.form-field label {
		margin-bottom: 0.35rem;
	}

	.form-input,
	.form-textarea {
		resize: vertical;
	}

	.btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.form-row {
		display: flex;
		gap: 1.5rem;
		margin-bottom: 1rem;
	}

	.checkbox-label {
		display: flex;
		align-items: center;
		gap: 0.4rem;
		font-size: 0.9rem;
		cursor: pointer;
	}

	.form-actions {
		display: flex;
		gap: 0.75rem;
	}

	.loading-text,
	.empty-text {
		color: #999;
		font-size: 0.9rem;
		text-align: center;
		padding: 1rem;
	}

	.list {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.list-item {
		display: flex;
		align-items: center;
		justify-content: space-between;
		background: rgba(255, 255, 255, 0.7);
		border: 1px solid rgba(107, 76, 154, 0.15);
		border-radius: 14px;
		padding: 0.75rem 1rem;
		gap: 1rem;
	}

	.item-info {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		flex: 1;
		min-width: 0;
	}

	.item-title {
		font-size: 0.9rem;
		color: #333;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.item-status {
		font-size: 0.75rem;
		padding: 0.15rem 0.5rem;
		border-radius: 8px;
		background: #e8f5e9;
		color: #27ae60;
		flex-shrink: 0;
	}

	.item-status.hidden {
		background: #f5f5f5;
		color: #999;
	}

	.item-actions {
		display: flex;
		gap: 0.4rem;
		flex-shrink: 0;
	}

	.btn-sm {
		padding: 0.3rem 0.65rem;
		border-radius: 8px;
		border: 1px solid rgba(107, 76, 154, 0.3);
		background: transparent;
		color: #6b4c9a;
		font-size: 0.8rem;
		cursor: pointer;
		transition: background 0.2s;
	}

	.btn-sm:hover {
		background: rgba(107, 76, 154, 0.08);
	}

	.btn-sm.btn-danger {
		border-color: rgba(192, 57, 43, 0.3);
		color: #c0392b;
	}

	.btn-sm.btn-danger:hover {
		background: rgba(192, 57, 43, 0.08);
	}
</style>
