// src/components/mumble/MumbleStatusPanel.tsx
import { useCallback, useEffect, useRef, useState } from 'react';

import { useMumbleClientSnapshot } from '../../hooks/mumble-client';
import { createMumbleClient, type MumbleClient } from '../../lib/mumble/client';
import { createChannelNameMap, countUsersByChannel } from '../../lib/mumble/utils';
import type { ApiResponse, MumbleProxyConfig, MumbleProxyHealth } from '../../lib/types';
import styles from './MumbleStatusPanel.module.css';

const HEALTH_REFRESH_INTERVAL_MS = 15_000;

function classNames(...names: Array<string | false | null | undefined>): string {
	return names
		.filter((name): name is string => typeof name === 'string')
		.map((name) => styles[name])
		.join(' ');
}

function isAbortError(error: unknown): boolean {
	return error instanceof DOMException && error.name === 'AbortError';
}

function formatTime(timestamp: number): string {
	return new Date(timestamp).toLocaleString('zh-CN', {
		month: '2-digit',
		day: '2-digit',
		hour: '2-digit',
		minute: '2-digit',
		second: '2-digit'
	});
}

function formatDateTime(timestamp: number): string | undefined {
	const date = new Date(timestamp);
	return Number.isNaN(date.valueOf()) ? undefined : date.toISOString();
}

function formatHealthEndpoint(url: string): string {
	try {
		return new URL(url).host;
	} catch {
		return url;
	}
}

export default function MumbleStatusPanel() {
	const [loading, setLoading] = useState(true);
	const [configError, setConfigError] = useState('');
	const [healthError, setHealthError] = useState('');
	const [refreshingHealth, setRefreshingHealth] = useState(false);
	const [proxyHealth, setProxyHealth] = useState<MumbleProxyHealth | null>(null);
	const [client, setClient] = useState<MumbleClient | null>(null);
	const clientState = useMumbleClientSnapshot(client);

	const mountedRef = useRef(false);
	const clientRef = useRef<MumbleClient | null>(null);
	const configControllerRef = useRef<AbortController | null>(null);
	const healthControllerRef = useRef<AbortController | null>(null);
	const healthRequestRef = useRef<Promise<void> | null>(null);
	const healthTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

	const performHealthRefresh = useCallback(async (): Promise<void> => {
		if (mountedRef.current) {
			setRefreshingHealth(true);
			setHealthError('');
		}
		const controller = new AbortController();
		healthControllerRef.current = controller;

		try {
			const response = await fetch('/api/admin/mumble/health', {
				headers: { Accept: 'application/json' },
				signal: controller.signal
			});
			const data: ApiResponse<MumbleProxyHealth> = await response.json();
			if (!response.ok || !data.success || !data.data) {
				throw new Error(data.error || `健康检查失败（HTTP ${response.status}）`);
			}
			if (mountedRef.current && !controller.signal.aborted) setProxyHealth(data.data);
		} catch (error) {
			if (!isAbortError(error) && mountedRef.current) {
				setHealthError(error instanceof Error ? error.message : '获取代理健康状态失败');
			}
		} finally {
			if (healthControllerRef.current === controller) {
				healthControllerRef.current = null;
				if (mountedRef.current) setRefreshingHealth(false);
			}
		}
	}, []);

	const refreshHealth = useCallback(async (): Promise<void> => {
		if (healthRequestRef.current) return healthRequestRef.current;
		const request = performHealthRefresh();
		healthRequestRef.current = request;
		try {
			await request;
		} finally {
			if (healthRequestRef.current === request) healthRequestRef.current = null;
		}
	}, [performHealthRefresh]);

	const scheduleHealthRefresh = useCallback(
		function scheduleHealthRefresh(): void {
			if (healthTimerRef.current) clearTimeout(healthTimerRef.current);
			if (!mountedRef.current) return;
			healthTimerRef.current = setTimeout(() => {
				healthTimerRef.current = null;
				void refreshHealth().finally(() => {
					if (mountedRef.current) scheduleHealthRefresh();
				});
			}, HEALTH_REFRESH_INTERVAL_MS);
		},
		[refreshHealth]
	);

	useEffect(() => {
		let cancelled = false;
		mountedRef.current = true;
		const configController = new AbortController();
		configControllerRef.current = configController;

		void (async () => {
			const healthRefresh = refreshHealth();
			let config: MumbleProxyConfig | null = null;
			try {
				const response = await fetch('/api/mumble/config', {
					signal: configController.signal
				});
				const data: ApiResponse<MumbleProxyConfig> = await response.json();
				if (response.ok && data.success && data.data) {
					config = data.data;
				} else if (!cancelled && mountedRef.current) {
					setConfigError(data.error || 'Mumble 代理配置不可用');
				}
			} catch (error) {
				if (!isAbortError(error) && !cancelled && mountedRef.current) {
					setConfigError('无法读取 Mumble 代理配置');
				}
			}

			if (!cancelled && mountedRef.current && !configController.signal.aborted && config) {
				const nextClient = createMumbleClient({
					config,
					nickname: `监控-${Math.floor(Math.random() * 9000 + 1000)}`,
					mode: 'monitor'
				});
				clientRef.current = nextClient;
				setClient(nextClient);
				nextClient.connect();
			}
			if (!cancelled && mountedRef.current) setLoading(false);

			await healthRefresh;
			if (!cancelled && mountedRef.current) scheduleHealthRefresh();
		})();

		return () => {
			cancelled = true;
			mountedRef.current = false;
			configController.abort();
			if (configControllerRef.current === configController) {
				configControllerRef.current = null;
			}
			healthControllerRef.current?.abort();
			healthControllerRef.current = null;
			healthRequestRef.current = null;
			if (healthTimerRef.current) clearTimeout(healthTimerRef.current);
			healthTimerRef.current = null;
			clientRef.current?.destroy();
			clientRef.current = null;
		};
	}, [refreshHealth, scheduleHealthRefresh]);

	const channelNameMap = createChannelNameMap(clientState.channels);
	const visibleUsers = clientState.users.filter((user) => user.sessionId !== clientState.sessionId);
	const usersByChannel = countUsersByChannel(visibleUsers);
	const recentMessages = [...clientState.messages].slice(-16).reverse();
	let monitorStatusText = '监控尚未连接';
	if (clientState.reconnecting) monitorStatusText = '监控连接重连中';
	else if (clientState.status === 'connecting') monitorStatusText = '监控连接建立中';
	else if (clientState.connected) monitorStatusText = '监控连接已就绪';
	else if (configError) monitorStatusText = '监控不可用';

	function getChannelName(channelId: number): string {
		return channelNameMap.get(channelId) ?? `频道 #${channelId}`;
	}

	async function handleManualHealthRefresh(): Promise<void> {
		await refreshHealth();
		scheduleHealthRefresh();
	}

	function handleReconnect(): void {
		clientRef.current?.reconnect();
		void handleManualHealthRefresh();
	}

	return (
		<div className={classNames('mumble-status-panel')}>
			<div className={classNames('panel-header')}>
				<div>
					<h2>🎧 Mumble 状态面板</h2>
					<p>
						该页面会以只读监控身份连接 Mumble 代理，展示当前健康状态、频道、在线用户与最近文字消息。
					</p>
				</div>

				<div className={classNames('panel-actions')}>
					<button
						className={classNames('action-btn', 'soft')}
						type="button"
						onClick={() => void handleManualHealthRefresh()}
						disabled={refreshingHealth}
					>
						{refreshingHealth ? '刷新中...' : '刷新健康'}
					</button>
					<button
						className={classNames('action-btn')}
						type="button"
						onClick={handleReconnect}
						disabled={loading}
					>
						重连监控
					</button>
				</div>
			</div>

			{configError && (
				<div className={classNames('alert', 'alert-error')} role="alert">
					❌ {configError}
				</div>
			)}

			{healthError && (
				<div className={classNames('alert', 'alert-error')} role="alert">
					❌ {healthError}
				</div>
			)}

			<div className={classNames('summary-grid')}>
				<section
					className={classNames('summary-card')}
					aria-live="polite"
					aria-busy={refreshingHealth}
				>
					<h3>代理健康</h3>
					{proxyHealth ? (
						<>
							<div className={classNames('status-line')}>
								<span
									className={classNames('status-dot', proxyHealth.healthy && 'healthy')}
									aria-hidden="true"
								/>
								<strong>{proxyHealth.healthy ? '运行正常' : '状态异常'}</strong>
							</div>
							<p>目标：{formatHealthEndpoint(proxyHealth.url)}</p>
							<p>响应：{proxyHealth.message}</p>
							<p>更新时间：{formatTime(proxyHealth.checkedAt)}</p>
						</>
					) : (
						<p>{loading ? '正在读取健康信息...' : '暂无健康数据'}</p>
					)}
				</section>

				<section className={classNames('summary-card')}>
					<h3>监控连接</h3>
					<div className={classNames('status-line')}>
						<span
							className={classNames('status-dot', clientState.connected && 'healthy')}
							aria-hidden="true"
						/>
						<strong>{monitorStatusText}</strong>
					</div>
					<p>昵称：{clientState.username || '等待连接中...'}</p>
					<p>频道数：{clientState.channels.length}</p>
					<p>在线用户：{visibleUsers.length}</p>
				</section>

				<section className={classNames('summary-card')}>
					<h3>最近活动</h3>
					<p>最近文字消息：{clientState.messages.length}</p>
					<p>
						当前频道：
						{clientState.currentChannelId === null
							? '未加入'
							: getChannelName(clientState.currentChannelId)}
					</p>
					<p>断线原因：{clientState.disconnectReason || '—'}</p>
				</section>
			</div>

			<div className={classNames('content-grid')}>
				<section className={classNames('content-card')}>
					<h3>频道列表</h3>
					{clientState.channels.length === 0 ? (
						<p className={classNames('empty-text')}>
							{loading ? '等待频道数据...' : '暂无频道数据'}
						</p>
					) : (
						<div className={classNames('table-wrap')}>
							<table aria-label="Mumble 频道列表">
								<thead>
									<tr>
										<th>频道</th>
										<th>在线人数</th>
										<th>描述</th>
									</tr>
								</thead>
								<tbody>
									{clientState.channels.map((channel) => (
										<tr key={channel.id}>
											<td>{channel.name}</td>
											<td>{usersByChannel.get(channel.id) ?? 0}</td>
											<td>{channel.description || '—'}</td>
										</tr>
									))}
								</tbody>
							</table>
						</div>
					)}
				</section>

				<section className={classNames('content-card')}>
					<h3>在线用户</h3>
					{visibleUsers.length === 0 ? (
						<p className={classNames('empty-text')}>
							{loading ? '等待在线用户...' : '暂无在线用户'}
						</p>
					) : (
						<div className={classNames('table-wrap')}>
							<table aria-label="Mumble 在线用户">
								<thead>
									<tr>
										<th>昵称</th>
										<th>所在频道</th>
										<th>静音</th>
										<th>耳聋</th>
									</tr>
								</thead>
								<tbody>
									{visibleUsers.map((user) => (
										<tr key={user.sessionId}>
											<td>{user.name}</td>
											<td>{getChannelName(user.channelId)}</td>
											<td>{user.muted ? '是' : '否'}</td>
											<td>{user.deafened ? '是' : '否'}</td>
										</tr>
									))}
								</tbody>
							</table>
						</div>
					)}
				</section>
			</div>

			<section className={classNames('content-card', 'messages-card')}>
				<h3>最近文字消息</h3>
				{recentMessages.length === 0 ? (
					<p className={classNames('empty-text')}>
						{loading ? '等待文本消息...' : '当前会话尚未收到文字消息'}
					</p>
				) : (
					<div className={classNames('message-list')}>
						{recentMessages.map((message) => (
							<article className={classNames('message-item')} key={message.id}>
								<div className={classNames('message-meta')}>
									<strong>{message.sender}</strong>
									<span>{getChannelName(message.channelId)}</span>
									<time dateTime={formatDateTime(message.timestamp)}>
										{formatTime(message.timestamp)}
									</time>
								</div>
								<p>{message.message}</p>
							</article>
						))}
					</div>
				)}
			</section>
		</div>
	);
}

// src/lib/components/MumbleStatusPanel.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import {
		createInitialMumbleClientSnapshot,
		createMumbleClient,
		type MumbleClientSnapshot
	} from '$lib/mumble/client';
	import { createChannelNameMap, countUsersByChannel } from '$lib/mumble/utils';
	import type { ApiResponse, MumbleProxyConfig, MumbleProxyHealth } from '$lib/types';

	let loading = $state(true);
	let configError = $state('');
	let healthError = $state('');
	let refreshingHealth = $state(false);
	let clientState = $state<MumbleClientSnapshot>(createInitialMumbleClientSnapshot());
	let proxyHealth = $state<MumbleProxyHealth | null>(null);

	let client: ReturnType<typeof createMumbleClient> | null = null;
	let unsubscribeClient: (() => void) | null = null;
	let healthTimer: ReturnType<typeof setTimeout> | null = null;
	let healthRequest: Promise<void> | null = null;
	let healthController: AbortController | null = null;
	let destroyed = false;
	const HEALTH_REFRESH_INTERVAL_MS = 15_000;

	const channelNameMap = $derived(createChannelNameMap(clientState.channels));
	const visibleUsers = $derived(
		clientState.users.filter((user) => user.sessionId !== clientState.sessionId)
	);
	const usersByChannel = $derived(countUsersByChannel(visibleUsers));
	const recentMessages = $derived([...clientState.messages].slice(-16).reverse());
	const monitorStatusText = $derived.by(() => {
		if (clientState.reconnecting) {
			return '监控连接重连中';
		}
		if (clientState.status === 'connecting') {
			return '监控连接建立中';
		}
		if (clientState.connected) {
			return '监控连接已就绪';
		}
		if (configError) {
			return '监控不可用';
		}
		return '监控尚未连接';
	});

	async function fetchMumbleConfig(): Promise<MumbleProxyConfig | null> {
		try {
			const res = await fetch('/api/mumble/config');
			const data: ApiResponse<MumbleProxyConfig> = await res.json();
			if (res.ok && data.success && data.data) {
				return data.data;
			}
			configError = data.error || 'Mumble 代理配置不可用';
		} catch {
			configError = '无法读取 Mumble 代理配置';
		}
		return null;
	}

	async function performHealthRefresh(): Promise<void> {
		refreshingHealth = true;
		healthError = '';
		const controller = new AbortController();
		healthController = controller;
		try {
			const response = await fetch('/api/admin/mumble/health', {
				headers: { Accept: 'application/json' },
				signal: controller.signal
			});
			const data: ApiResponse<MumbleProxyHealth> = await response.json();
			if (!response.ok || !data.success || !data.data) {
				throw new Error(data.error || `健康检查失败（HTTP ${response.status}）`);
			}
			proxyHealth = data.data;
		} catch (caught) {
			if (caught instanceof DOMException && caught.name === 'AbortError') return;
			healthError = caught instanceof Error ? caught.message : '获取代理健康状态失败';
		} finally {
			if (healthController === controller) {
				healthController = null;
				refreshingHealth = false;
			}
		}
	}

	async function refreshHealth(): Promise<void> {
		if (healthRequest) return healthRequest;
		healthRequest = performHealthRefresh();
		try {
			await healthRequest;
		} finally {
			healthRequest = null;
		}
	}

	function scheduleHealthRefresh(): void {
		if (healthTimer) clearTimeout(healthTimer);
		if (destroyed) return;
		healthTimer = setTimeout(async () => {
			await refreshHealth();
			scheduleHealthRefresh();
		}, HEALTH_REFRESH_INTERVAL_MS);
	}

	async function handleManualHealthRefresh(): Promise<void> {
		await refreshHealth();
		scheduleHealthRefresh();
	}

	function handleReconnect(): void {
		client?.reconnect();
		void handleManualHealthRefresh();
	}

	function formatTime(timestamp: number): string {
		return new Date(timestamp).toLocaleString('zh-CN', {
			month: '2-digit',
			day: '2-digit',
			hour: '2-digit',
			minute: '2-digit',
			second: '2-digit'
		});
	}

	function getChannelName(channelId: number): string {
		return channelNameMap.get(channelId) ?? `频道 #${channelId}`;
	}

	function formatHealthEndpoint(url: string): string {
		try {
			return new URL(url).host;
		} catch {
			return url;
		}
	}

	onMount(() => {
		let cancelled = false;
		destroyed = false;

		(async () => {
			const healthRefresh = refreshHealth();
			const config = await fetchMumbleConfig();

			if (cancelled) return;
			if (!config) {
				loading = false;
			} else {
				client = createMumbleClient({
					config,
					nickname: `监控-${Math.floor(Math.random() * 9000 + 1000)}`,
					mode: 'monitor'
				});
				unsubscribeClient = client.state.subscribe((nextState) => {
					clientState = nextState;
				});
				client.connect();
				loading = false;
			}

			await healthRefresh;
			if (!cancelled) scheduleHealthRefresh();
		})();

		return () => {
			cancelled = true;
			destroyed = true;
			unsubscribeClient?.();
			client?.destroy();
			healthController?.abort();
			if (healthTimer) clearTimeout(healthTimer);
		};
	});
</script>

<div class="mumble-status-panel">
	<div class="panel-header">
		<div>
			<h2>🎧 Mumble 状态面板</h2>
			<p>
				该页面会以只读监控身份连接 Mumble 代理，展示当前健康状态、频道、在线用户与最近文字消息。
			</p>
		</div>

		<div class="panel-actions">
			<button
				class="action-btn soft"
				type="button"
				onclick={() => void handleManualHealthRefresh()}
				disabled={refreshingHealth}
			>
				{refreshingHealth ? '刷新中...' : '刷新健康'}
			</button>
			<button class="action-btn" type="button" onclick={handleReconnect} disabled={loading}
				>重连监控</button
			>
		</div>
	</div>

	{#if configError}
		<div class="alert alert-error" role="alert">❌ {configError}</div>
	{/if}

	{#if healthError}
		<div class="alert alert-error" role="alert">❌ {healthError}</div>
	{/if}

	<div class="summary-grid">
		<section class="summary-card" aria-live="polite" aria-busy={refreshingHealth}>
			<h3>代理健康</h3>
			{#if proxyHealth}
				<div class="status-line">
					<span class="status-dot" class:healthy={proxyHealth.healthy}></span>
					<strong>{proxyHealth.healthy ? '运行正常' : '状态异常'}</strong>
				</div>
				<p>目标：{formatHealthEndpoint(proxyHealth.url)}</p>
				<p>响应：{proxyHealth.message}</p>
				<p>更新时间：{formatTime(proxyHealth.checkedAt)}</p>
			{:else}
				<p>{loading ? '正在读取健康信息...' : '暂无健康数据'}</p>
			{/if}
		</section>

		<section class="summary-card">
			<h3>监控连接</h3>
			<div class="status-line">
				<span class="status-dot" class:healthy={clientState.connected}></span>
				<strong>{monitorStatusText}</strong>
			</div>
			<p>昵称：{clientState.username || '等待连接中...'}</p>
			<p>频道数：{clientState.channels.length}</p>
			<p>在线用户：{visibleUsers.length}</p>
		</section>

		<section class="summary-card">
			<h3>最近活动</h3>
			<p>最近文字消息：{clientState.messages.length}</p>
			<p>
				当前频道：{clientState.currentChannelId === null
					? '未加入'
					: getChannelName(clientState.currentChannelId)}
			</p>
			<p>断线原因：{clientState.disconnectReason || '—'}</p>
		</section>
	</div>

	<div class="content-grid">
		<section class="content-card">
			<h3>频道列表</h3>
			{#if clientState.channels.length === 0}
				<p class="empty-text">{loading ? '等待频道数据...' : '暂无频道数据'}</p>
			{:else}
				<div class="table-wrap">
					<table>
						<thead>
							<tr>
								<th>频道</th>
								<th>在线人数</th>
								<th>描述</th>
							</tr>
						</thead>
						<tbody>
							{#each clientState.channels as channel (channel.id)}
								<tr>
									<td>{channel.name}</td>
									<td>{usersByChannel.get(channel.id) ?? 0}</td>
									<td>{channel.description || '—'}</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			{/if}
		</section>

		<section class="content-card">
			<h3>在线用户</h3>
			{#if visibleUsers.length === 0}
				<p class="empty-text">{loading ? '等待在线用户...' : '暂无在线用户'}</p>
			{:else}
				<div class="table-wrap">
					<table>
						<thead>
							<tr>
								<th>昵称</th>
								<th>所在频道</th>
								<th>静音</th>
								<th>耳聋</th>
							</tr>
						</thead>
						<tbody>
							{#each visibleUsers as user (user.sessionId)}
								<tr>
									<td>{user.name}</td>
									<td>{getChannelName(user.channelId)}</td>
									<td>{user.muted ? '是' : '否'}</td>
									<td>{user.deafened ? '是' : '否'}</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			{/if}
		</section>
	</div>

	<section class="content-card messages-card">
		<h3>最近文字消息</h3>
		{#if recentMessages.length === 0}
			<p class="empty-text">{loading ? '等待文本消息...' : '当前会话尚未收到文字消息'}</p>
		{:else}
			<div class="message-list">
				{#each recentMessages as message (message.id)}
					<article class="message-item">
						<div class="message-meta">
							<strong>{message.sender}</strong>
							<span>{getChannelName(message.channelId)}</span>
							<time>{formatTime(message.timestamp)}</time>
						</div>
						<p>{message.message}</p>
					</article>
				{/each}
			</div>
		{/if}
	</section>
</div>

<style>
	.mumble-status-panel {
		max-width: 1100px;
		margin: 0 auto;
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
		min-width: 0;
	}

	.panel-header {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
		gap: 1rem;
		flex-wrap: wrap;
	}

	.panel-header h2 {
		margin: 0 0 0.35rem;
		font-family: 'Fredoka', sans-serif;
		color: #6b4c9a;
		font-size: 1.6rem;
	}

	.panel-header p {
		margin: 0;
		max-width: 700px;
		color: #8b7ba8;
		line-height: 1.5;
	}

	.panel-actions {
		display: flex;
		gap: 0.6rem;
		flex-wrap: wrap;
	}

	.action-btn {
		border: none;
		border-radius: 12px;
		padding: 0.65rem 1rem;
		background: linear-gradient(135deg, #ff8fbe 0%, #bfa5ff 100%);
		color: #2f1a52;
		font-weight: 700;
		cursor: pointer;
	}

	.action-btn:disabled {
		cursor: not-allowed;
		opacity: 0.6;
	}

	.action-btn:focus-visible {
		outline: 3px solid rgba(107, 76, 154, 0.28);
		outline-offset: 2px;
	}

	.action-btn.soft {
		background: rgba(107, 76, 154, 0.12);
		color: #6b4c9a;
	}

	.alert {
		padding: 0.9rem 1rem;
		border-radius: 14px;
	}

	.alert-error {
		background: rgba(255, 107, 107, 0.15);
		color: #c8556b;
	}

	.summary-grid,
	.content-grid {
		display: grid;
		gap: 1rem;
		min-width: 0;
	}

	.summary-grid {
		grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
	}

	.content-grid {
		grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
	}

	.summary-card,
	.content-card {
		background: rgba(255, 255, 255, 0.78);
		backdrop-filter: blur(10px);
		border-radius: 18px;
		padding: 1rem 1.1rem;
		box-shadow: 0 8px 24px rgba(107, 76, 154, 0.08);
		min-width: 0;
	}

	.summary-card h3,
	.content-card h3 {
		margin: 0 0 0.75rem;
		color: #6b4c9a;
		font-size: 1.05rem;
	}

	.summary-card p {
		margin: 0.35rem 0 0;
		color: #6a5b86;
		font-size: 0.9rem;
	}

	.status-line {
		display: flex;
		align-items: center;
		gap: 0.45rem;
	}

	.status-dot {
		width: 10px;
		height: 10px;
		border-radius: 50%;
		background: #ffc857;
	}

	.status-dot.healthy {
		background: #4caf50;
	}

	.table-wrap {
		overflow-x: auto;
		border-radius: 14px;
	}

	table {
		width: 100%;
		border-collapse: collapse;
		background: rgba(255, 255, 255, 0.55);
	}

	th,
	td {
		padding: 0.7rem 0.75rem;
		text-align: left;
		border-bottom: 1px solid rgba(107, 76, 154, 0.08);
		font-size: 0.9rem;
		color: #554773;
	}

	th {
		color: #6b4c9a;
		font-weight: 700;
		background: rgba(107, 76, 154, 0.05);
	}

	.messages-card {
		padding-bottom: 1.15rem;
	}

	.message-list {
		display: flex;
		flex-direction: column;
		gap: 0.7rem;
	}

	.message-item {
		background: rgba(244, 239, 255, 0.9);
		border-radius: 14px;
		padding: 0.8rem 0.9rem;
	}

	.message-meta {
		display: flex;
		gap: 0.75rem;
		flex-wrap: wrap;
		align-items: center;
		margin-bottom: 0.35rem;
		font-size: 0.78rem;
		color: #7b65a1;
	}

	.message-item p {
		margin: 0;
		color: #4d3a70;
		word-break: break-word;
	}

	.empty-text {
		margin: 0;
		color: #9787b8;
		font-size: 0.9rem;
	}

	@media (max-width: 768px) {
		.panel-header {
			flex-direction: column;
		}

		.panel-actions {
			width: 100%;
		}

		.action-btn {
			flex: 1;
		}

		.content-grid {
			grid-template-columns: minmax(0, 1fr);
		}
	}

	@media (max-width: 390px) {
		.panel-actions {
			flex-direction: column;
		}

		.summary-card,
		.content-card {
			padding: 0.9rem;
		}

		th,
		td {
			padding: 0.6rem;
		}
	}
</style>
